AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CybageTanviSSM:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://cybage-tanvi-poc/Cybage_Tanvi_SSM-d450f8d7-07fa-456e-a444-a8bc4fd3d606.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::543816070942:role/lambda_basic_execution'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: block/allow
      TopicName: cybage-alm-tanvi-sns
