AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Parameters:
   BucketName:
        Type: String
    CodeKey:
        Type: String
Resources:
  CybageTanviSSM:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: 
          Bucket: !Ref BucketName
          Key: !Ref CodeKey
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::543816070942:role/lambda_basic_execution'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: block/allow
      TopicName: cybage-alm-tanvi-sns
